spring:
  zipkin:
    base-url: http://192.168.206.131:9411
  sleuth:
    sampler:
      probability: 1
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://dq0:123456@192.168.206.131:8760/eureka,http://dq1:123456@192.168.206.131:8761/eureka,http://dq2:123456@192.168.206.131:8762/eureka
    healthcheck:
      #      用于开启健康检查，需要加入 actuator 依赖
      enabled: true
  instance:
    #    采用 ip 注册
    preferIpAddress: true
    #    定义实例 id 格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    #    默认 30 秒，表示 eureka client 发送心跳到 server 端的频率
    lease-renewal-interval-in-seconds: 10
    #    默认 90 秒，表示 eureka server 至上一次收到 client 的心跳之后等待下一次心跳的超时时间，在这段时间过后没有收到心跳就会移除该 instance （实例）
    lease-expiration-duration-in-seconds: 30

feign:
  compression:
    request:
      enabled: true
#      压缩的类型
      mime-types: test/xml,application/xml,application/json
#      最小压缩值的标准
      min-request-size: 2048
    response:
      enabled: true
  hystrix:
    enabled: true
